name: jsonwebtoken
description: A starting point for Dart libraries or applications.
version: 1.2.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  clock: ^1.1.1
  convert: ^3.1.1
  crypto: ^3.0.3

dev_dependencies:
  very_good_analysis: ^5.1.0
